### ISSUE TITLE
add tagged version to the repo?

### ISSUE THREAD

**Issue by wmginsberg** [webcomponents/slush-element#7]
Hey, this is an awesome element! Can you possibly add a tagged version to this repo? Thanks :)

**Comment by obetomuniz** [comment]
Yes @wmginsberg Thanks for report :)

**Comment by wmginsberg** [comment]
sweet, and one more thing: can you add a bower.json? that would be great!

**Comment by obetomuniz** [comment]
Sorry @wmginsberg but what you want to mean about `add a bower.json`? In the generator or in the templates?

**Comment by wmginsberg** [comment]
in the main repo, it should list all of your bower dependencies, app-name, license, repo, authors, etc.  

check out paper-inputs bower.json 
https://github.com/PolymerElements/paper-input/blob/master/bower.json

**Comment by obetomuniz** [comment]
Oh! In the case, `slush-element` is not a bower package, it's a Slush Generator that helps you create Custom Elements using the Polymer, X-Tags or VanillaJS way 😄
